### ISSUE TITLE
MeteoFrance AROME

### ISSUE THREAD

**Issue by insatomcat** [amsokol/go-grib2#4]
Hi, I saw in the other opened issue that you were working on meteofrance data.
Right now it's not working, giving : 

> $ go run main.go AROME_0.01_SP1_37H_201711231200.grib2 
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/amsokol/go-grib2.Read(0xc42206e000, 0x1835c86, 0x1fffe00, 0x1835c86, 0x1fffe00, 0x0, 0x0, 0xc42003dc00)
	/home/user/go/src/github.com/amsokol/go-grib2/reader.go:97 +0x9af
main.main()
	/home/user/main.go:27 +0x1eb
exit status 2

Just in case I tried with the opened pullrequest : 

> $ go run main.go AROME_0.01_SP1_37H_201711231200.grib2 
2017/11/23 21:33:04 packing type [40] not supported
exit status 1

**Comment by amsokol** [comment]
Hi,

go-grib2 does not support jpeg2000 packing type.
I recommend you try another my lib:
https://github.com/amsokol/go-eccodes

see examples in `cmd` folder
